### ISSUE TITLE
Sort transactions optional param

### ISSUE THREAD

**Issue by lthiery** [helium/blockchain-http#123]
Sometimes it could be useful to get transactions from beginning to end instead of the default most recent to beginning. 

For example, I'm trying to find when a hotspot was first added, I have to go to hotspot activity and go through transactions until I get to the beginning of time. This could be part of whats returned from the hotspot list endpoint as well (/hotspots) but it doesn't appear to be that way.

Another example, if I'm trying to rederive a balance at a certain date, I'll want to look at the account transactions in reverse order.

**Comment by madninja** [comment]
There are a few problems with sorting transactions from block 1 up ,but the main one is that It's a non-deterministic ending.. I.e. the cursor can never be sure when it's "finished". 

I think that you're trying to actually tryin to achieve something by asking for all the transactions that perhaps a more specialized route could get for you more effectively? 

Like when a hotspots was first added: 

```
http --body get https://api.helium.io/v1/hotspots/name/curved-bubblegum-worm
{
    "data": [
        {
            "address": "11YxTkeuixD7QZjoez9vpuaSFfZG6bMgkLVM1XWF7yEsHUAW1x7",
            "block": 547176,
            "block_added": 542322,
            "geocode": {
                "city_id": "bGFrZSBlbHNpbm9yZWNhbGlmb3JuaWF1bml0ZWQgc3RhdGVz",
                "long_city": "Lake Elsinore",
                "long_country": "United States",
                "long_state": "California",
                "long_street": "Silverwood Drive",
                "short_city": "Lake Elsinore",
                "short_country": "US",
                "short_state": "CA",
                "short_street": "Silverwood Dr"
            },
            "lat": 33.623169034238025,
            "lng": -117.30716427800822,
            "location": "8c29a08a8c169ff",
            "name": "curved-bubblegum-worm",
            "nonce": 1,
            "owner": "14ZuJR3wN6FV8hptRBKo12fZ6x1foRXWNo77erEN3WzSECExFe7",
            "score": 0.25,
            "score_update_height": 542323,
            "status": {
                "height": 1,
                "online": "offline"
            }
        }
    ]
}
```

See the `first_block ` field which tells you when a hotspot was added to the blockchain. 

We could do a more specialized route for getting an account balance at a certain block/date?

**Comment by madninja** [comment]
@lthiery unless you feel strongly I'm going to close this due to inactivity
