### ISSUE TITLE
Helium SDK

### ISSUE THREAD

**Issue by roberthenderson** [helium/blockchain-http#127]
I've played around with the current v1 API and hit quite a few roadblocks that make developing an app quite cumbersome because it requires a lot of network requests and heavy client-side processing to get the data you want

TL;DR: An API should be designed with implementation in mind, not to deliver a big dump of data that can then be parsed on the client.

I'm a fan of designing an API so that it only delivers the minimum data needed for the current request. I don't think the hotspots API makes much sense for any application other than one that would literally display every hotspot's stats on the same page. It would make more sense to me to just have the hotspots API deliver name and address, ideally as a map (I know y'all are switching to use algolia for search, but if a community developer wanted a simple search bar, a map of hotspot names should be fine). Then, you can use the address to request more information about a given hotspot. 

Same with the blocks API. There doesn't seem to be a need to have an endpoint that delivers all blocks with all block data.

It also depends what are your goals for these endpoints? Are they meant to just power explorer or are there plans to have an SDK that makes it easy for the community to build out apps for their own needs? If the latter, it should be designed in a way where the patterns are easy to understand and be able to "drill down" to get more refined data. 

For example, say I want to find the last time a hotspot's witness witnessed the hotspot (say I had a hotspot page that showed its witnesses and next to each there is a "View Last Witness" button). Currently, I would need to call /hotspots/:address/challenges, loop through all of the challenges, and within each challenge, loop through all of the witnesses and keep doing so until I find the witness address I'm looking for. But ideally, all of that work should be done on the server that delivers the response. I should be able to call /hotspots/:address/witnesses/:address/challenges/offset/1 and be given the challenge in which this witness was last involved. If I change 1 to 5, it increases the offset and gives me the last 5. This allows the developer to use the Helium SDK/API to get specific data without heavy client-side processing or making multiple network requests.

**Comment by madninja** [comment]
The goals of the REST API are to power the most common queries done by apps and community in a simple way. I know it could be more powerful to support use cases so perhaps either: 1. propose new APIs that help your use case or 2. start a community effort around a generic graphQL api that supports arbitrarily complex queries. I'd be very excited about either/both of those!
