### ISSUE TITLE
Feature: earnings buckets

### ISSUE THREAD

**Issue by allenan** [helium/blockchain-http#129]
We want to be able to answer questions like "what was the total HNT earned by all hotspots on the network between two timestamps?" and "what was the median hotspot earning between those timestamps?". We also want to be able to separate out earnings by "buckets" between those timestamps. So for a given hotspot, we could chart a bar graph for each day's earnings within the past week. Ideally the design of this API will be flexible enough to serve different use cases.

**Comment by madninja** [comment]
@allenan for clarification: How do buckets and the median values between two timestamps relate to each other?

**Comment by allenan** [comment]
the median would probably be top level between the timestamps, separate from the buckets

**Comment by madninja** [comment]
So technically a different endpoint or param I guess?
