### ISSUE TITLE
inconsistent results from API queries

### ISSUE THREAD

**Issue by foster805** [helium/blockchain-http#130]
Having a problem with hotspot rewards API calls where the rewards for a longer period doesn't equal the sum of the rewards of shorter periods within it.  For example: 
The API returns rewards for 10/1 to 10/27:  33108296896
The API returns rewards for 10/27 to 10/28:  849902422
sum of these:  33958199318
but the API returns rewards for 10/01 to 10/28:  34036803710, or 78604392 greater than the sum of the individual periods.

[https://api.helium.io/v1/hotspots/1162fRqWoUGd8DUexz92d3ZsVaZre4wjXFTWEmLjK4WnXkmZMss/rewards/sum/?min_time=2020-10-01T00:00:00&max_time=2020-10-27T00:00:00]
{"data":{"sum":"33108296896","min_time":"2020-10-01T00:00:00Z","max_time":"2020-10-27T00:00:00Z"}}

[https://api.helium.io/v1/hotspots/1162fRqWoUGd8DUexz92d3ZsVaZre4wjXFTWEmLjK4WnXkmZMss/rewards/sum/?min_time=2020-10-27T00:00:00&max_time=2020-10-28T00:00:00]
{"data":{"sum":"849902422","min_time":"2020-10-27T00:00:00Z","max_time":"2020-10-28T00:00:00Z"}}

[https://api.helium.io/v1/hotspots/1162fRqWoUGd8DUexz92d3ZsVaZre4wjXFTWEmLjK4WnXkmZMss/rewards/sum/?min_time=2020-10-01T00:00:00&max_time=2020-10-28T00:00:00]
{"data":{"sum":"34036803710","min_time":"2020-10-01T00:00:00Z","max_time":"2020-10-28T00:00:00Z"}}

**Comment by abhay** [comment]
Nice find @foster805 and nice fix, @madninja
