### ISSUE TITLE
Get rewards bucketed by given timezone offset

### ISSUE THREAD

**Issue by danielcolinjames** [helium/blockchain-http#139]
I'm not sure how hard or feasible this would be, but it would be really useful if we could get the rewards sent back based on a timezone offset we pass into the request. And if one isn't specified it could return in UTC like it does now.

I think this would make it a lot easier to show users the earnings over certain time periods in a way that easily lines up with how they think about days. E.g. it can be kind of disorienting when Sitebot stops adding rewards to "Today" and it starts counting them for "Tomorrow".

So if we could for example take the user's local timezone offset and pass that as part of the request to get earnings bucketed by day at -8:00 offset, that would be great.

But maybe this wouldn't be feasible to add on the backend, or perhaps there's a client-side way we can do this even given the UTC buckets... I'm not sure. Timezone math is confusing me :)

**Comment by cokes518** [comment]
@madninja is there an update on this? having the timezone offset would unblock both explorer and hotspot app teams

**Comment by cokes518** [comment]
What do you think about rolling buckets of data instead of timezone offset? So bucket by last 24 hours worth of data instead of calculating based on timezone.

**Comment by allenan** [comment]
yeah both teams seem to be backing into rolling buckets right now, so I think supporting that in these routes would produce the "right" data from a user pov and would eliminate timezone complexity

**Comment by madninja** [comment]
hmm, but bucket how exactly? by hour for the last 24 hours? and the "current" hour would not be included since it's not complete yet?

**Comment by cokes518** [comment]
after the discussion today, it would make sense to move forward with this feature in place of #165 due to time constraints. If the app team has this route created, then the app can append other debiting and crediting transactions on top of the reward bucket to generate the account chart.

**Comment by madninja** [comment]
Fixed by #175 and #177
