### ISSUE TITLE
Rewards and stats for all hotspots

### ISSUE THREAD

**Issue by allenan** [helium/blockchain-http#142]
In addition to the rewards endpoints for individual hotspots and accounts provided here: https://github.com/helium/blockchain-http/issues/129, we need an additional endpoint that exposes rewards and stats across all hotspots.

I'd imagine the route would be: `/v1/hotspots/rewards/stats` and would take the same params as the other endpoints with regard to max/min time and bucket.

The one potentially tricky point is that in calculating the stats, the rewards should be considered per hotspot.

For example, if there were 5 hotspots in the entire network that were producing rewards for the week of 11/22, and their earnings for that week were:

- hotspot A: 100 HNT
- hotspot B: 500 HNT
- hotspot C: 300 HNT
- hotspot D: 100 HNT
- hotspot E: 200 HNT

If we requested min_time=2020-11-22 and max_time=2020-11-29 and bucket=week, we'd expect to see:

- total = 1200 HNT
- median = 300 HNT

Note there that the median reward for the week was hotspot C's total earnings for that week as compared to each of the other hotspots' total earnings for that week.

**Comment by madninja** [comment]
This is fixed by #177
