### ISSUE TITLE
Include location of hotspots in consensus transaction data

### ISSUE THREAD

**Issue by danielcolinjames** [helium/blockchain-http#145]
It would be awesome if the lat/lon of all 16 consensus group hotspots were included in the API response for a txn of type consensus_group_v1. I'm trying to plot them all, but I think right now the only way to do it is to make 16 separate requests of hotspot IDs to get their lat/lons

Right now that transaction type returns an array `members` of each hotspot's address in string format. It would be awesome if each element in `members` had at least:

- latitude
- longitude
- hotspot address

instead of just the hotspot address string

**Comment by madninja** [comment]
@danielcolinjames hmm.. vs looking at `/v1/hotspots/elected`? I've been trying to keep transactions as clean as possible, and adding these decorated transactions under different routes

**Comment by danielcolinjames** [comment]
@madninja  Ah, I didn't know about `/v1/hotspots/elected`! I imagine that returns the latest elected group? That looks great though! Is there a way to pass it an argument (block height, txn hash or something) to get that response for a given consensus group?

Sorry—stupid questions, but I'm not sure where to find documentation on that route 😅

**Comment by madninja** [comment]
that route is the "currently" elected consensus group.
