### ISSUE TITLE
Add hotspot earnings in account-rewards-sum API

### ISSUE THREAD

**Issue by wishplorer** [helium/blockchain-http#150]
Currently, Account-rewards-sum API (https://api.helium.io//v1/hotspots/:address/rewards/sum) only returns account earnings for given timeframe. If API could be modified to get rewards(sum) for all hotspot in an account broken at hotspot level along with Account earnings for given timeframe.

This would eliminate a need to make multiple API call at hotspot level, if account level API can breakdown hotspot earnings.

Current output:
{
    "data": {
        "max_time": "2020-08-29T00:00:00Z",
        "min_time": "2020-08-27T00:00:00Z",
        "sum": "10000"
    }
}

Suggested future output:

{
    "data": {
        "max_time": "2020-08-29T00:00:00Z",
        "min_time": "2020-08-27T00:00:00Z",
        "sum": "10000"
        "hotpsot": [
                            {"address": hotspot_address1,
                             "name": "name-of-hotspot1",
                             "sum": "3000"
                            },
                            {"address": hotspot_address2,
                             "name": "name-of-hotspot2",
                             "sum": "7000"
                            }
                          ]
                  }
}

**Comment by madninja** [comment]
I think we talked about this in Discord, right @wishplorer ? Getting rewards accumulated for an account is an expensive proposition already and breaking it down per hotspot in a single call would really make this quite slow. 

I'd suggest making multiple concurrent requests to the server and letting concurrency help you here?

**Comment by wishplorer** [comment]
Thanks . I am good with that.
