### ISSUE TITLE
Clear Individual witnesses after 7 days instead of resetting whole list

### ISSUE THREAD

**Issue by qwick745** [helium/blockchain-http#162]
To better reflect the most recent witnesses of a hotspot I would propose that witness lists not clear once every two weeks, but that an individual witness will remain visible for 7 days (~11,340) blocks after it was last witnessed. Numerous people are confused by having all witnesses drop at once, and this display that a hotspot has no witnesses is not accurate, especially even if successfully beaconed with multiple witnesses a short time before it's list clears.

I'm not sure exactly where this list is maintained, in explorer I imagine, and when it usually runs the process to delete the list, but as long as there is a way to see each witness's most recent time stamp (block#) of when it witnessed a hotspot, it could be set to delete after 11,340 or some other number of blocks. Not sure how often this would need to run to check the lists, at least once a day I'd think, or if simply every time a hotspot is c hallenged.

**Comment by madninja** [comment]
Fixed by #161 . Will deploy tomorrow morning PT
