### ISSUE TITLE
Add locations/:h3index route for geo details

### ISSUE THREAD

**Issue by danielcolinjames** [helium/blockchain-http#163]
Would be awesome to be able to get geo details for a given h3 index for example at /locations/:h3index, like in the response for a hotspot:
```json
geocode:
  cityId: "c2FuIGZyYW5jaXNjb2NhbGlmb3JuaWF1bml0ZWQgc3RhdGVz"
  longCity: "San Francisco"
  longCountry: "United States"
  longState: "California"
  longStreet: "Spear Street"
  shortCity: "SF"
  shortCountry: "US"
  shortState: "CA"
  shortStreet: "Spear St"
```

This came up for displaying nicer city/state/country info for the assert location transaction (https://github.com/helium/explorer/pull/136), and I'm sure could be used in other places as well

**Comment by allenan** [comment]
this seems like a bit of a strange general purpose API when we already have a pattern of including `geocode` data with api response objects that have an h3 location. could we just do that for the assert location transactions?

**Comment by madninja** [comment]
> this seems like a bit of a strange general purpose API when we already have a pattern of including `geocode` data with api response objects that have an h3 location. could we just do that for the assert location transactions?

Except that we don't have the pattern for transactions. The add-on data is only included in data that is _not_ in a transaction, but comes from some higher level ledger like view.
