### ISSUE TITLE
Add max_time and min_time as query params for witnesses endpoint

### ISSUE THREAD

**Issue by cokes518** [helium/blockchain-http#166]
https://api.helium.io/v1/hotspots/:address/witnesses

This route returns the current witnesses for a hotspot only - we'll need to add max_time and min_time as query params for this screen to work.

<img width="253" alt="image" src="https://user-images.githubusercontent.com/19331274/104515426-aa4cee80-55a7-11eb-86fb-cfde4cfb52d8.png">

**Comment by madninja** [comment]
The problem we have here is that the hotspot witnesses list already is a "union of all witnesses for the last 5 days", since the witness list is cleared randomly every two weeks. 

Is the above graph the witnesses per day? i.e. maybe this is a stats more than an exact number?

**Comment by cokes518** [comment]
The graph is indeed, witnesses per day.

**Comment by tyler-whitman** [comment]
For the designs we have

1. Per hour for last 24 hours
2. Per day for last 4, 14, 30 days

Not sure if the per hour is possible or makes sense?

**Comment by madninja** [comment]
It would be as long as you're ok with the odd 0 witness results after a witness reset

**Comment by madninja** [comment]
WIth #178:

1. Per hour for last 24 hours: /v1/hotspots/:address/witnesses/sum?min_time="-24 hour"&bucket=hour
2. Per day for last 4, 14, 30 days (example for 4 day): /v1/hotspots/:address/witnesses/sum?min_time="-4 day"&bucket=day
