### ISSUE TITLE
Add min_time and max_time parameters to hotspot challenge query

### ISSUE THREAD

**Issue by tyler-whitman** [helium/blockchain-http#172]
We need to be able to query https://developer.helium.com/blockchain/api/api-hotspots#hotspot-challenges by time periods to create charts for the mobile app.

The idea is to show challenge pass rate per day for last 7, 14, 30 days and per hour for the 24 hours.

I know we have also talked about this extensively but adding it here for discussion. Does it make sense to add a successful attribute to challenges on the backend?

UI:
![Screen Shot 2021-01-26 at 11 23 17 AM](https://user-images.githubusercontent.com/6345962/105894441-1fb5b780-5fc9-11eb-9e9e-c4d58a2a33a0.png)

**Comment by madninja** [comment]
oh this is more than min/max_time for challenges, this is actually bucketed stats for challenges.
