### ISSUE TITLE
Duplicated results in account rewards API

### ISSUE THREAD

**Issue by kklyandev** [helium/blockchain-http#174]
/accounts/14cWRnJk7oZDeRSfo9yS3jpWfQmqZxNEzxQoygkoPBixLVSQaTg/rewards?min_time=2020-06-05T00:00:00.000000&max_time=2020-06-16T07:00:00.000000 returns one page of 100 results and second page with 2 results where the first result from the second page duplicates the last result from the first page. Modifying the end date range to 2020-06-16T00:00:00.000000 returns 1 page with 1 result and second page with 99 results and no duplicates.

**Comment by kklyandev** [comment]
@madninja Not sure if you had the time to take a look at this... I found one more example where 2 transactions are duplicated. Here the last 2 from one page repeat as the first 2 on the next page:
https://api.helium.io/v1/accounts/14cWRnJk7oZDeRSfo9yS3jpWfQmqZxNEzxQoygkoPBixLVSQaTg/rewards?min_time=2020-12-01T00:00:00.000000&max_time=2021-01-01T00:00:00.000000&cursor=eyJ0eG4iOiJycTNTNlU0WktqY05wbnR6UDZHcnE1MWs2TnZuWGR6Z01lY2JkbEg1ZC1FIiwiZW5kX2Jsb2NrIjo2MTA1ODAsImJsb2NrIjo2MzU3MTEsImFuY2hvcl9ibG9jayI6NjU0OTAwfQ

https://api.helium.io/v1/accounts/14cWRnJk7oZDeRSfo9yS3jpWfQmqZxNEzxQoygkoPBixLVSQaTg/rewards?min_time=2020-12-01T00:00:00.000000&max_time=2021-01-01T00:00:00.000000&cursor=eyJ0eG4iOiJMMlFXekNzU2pvYU9fZ09SZDBMVm9WVk1ZQWZDb1YyU0s2SmtpazkzaEo4IiwiZW5kX2Jsb2NrIjo2MTA1ODAsImJsb2NrIjo2MjQ5MjEsImFuY2hvcl9ibG9jayI6NjU0OTAwfQ

**Comment by madninja** [comment]
Thanks for gathering them @kklyandev .. I'm looking at them shortly
