### ISSUE TITLE
Need apis for validator metrics

### ISSUE THREAD

**Issue by jdgemm** [helium/blockchain-http#176]
Need apis for validator metrics for both testnet and mainnet:

- provide total # of validator counts broken down by stake status (staked, cooldown, in consensus, online, offline)
 - amount of HNT staked (individual nodes and total)
 - HNT paid out to validator (individual nodes and total)
 - consensus group members and size
 - state of validator node (online, offline, in consensus, cooldown)
 - date of initial stake
 - amount of HNT in cooldown
 - total staked vs total supply vs total circulating supply

We'd leverage mainnet apis to provide a visuals on a validator section of explorer.

**Comment by madninja** [comment]
I believe this is all complete now @jdgemm

**Comment by OrmEmbaar** [comment]
> HNT paid out to validator (individual nodes and total)

Is this one complete? I am unable to find how to do this.

**Comment by madninja** [comment]
> > HNT paid out to validator (individual nodes and total)
> 
> Is this one complete? I am unable to find how to do this.

Yeah it's there under the `/v1/validators/:validator/rewards/sum` route just like it exists for hotspots.. It's missing api docs though, which will have to be added

**Comment by OrmEmbaar** [comment]
Thanks, though this does not appear to work for me. Using validator `1ZxmSuuWfhLRum45sgk8ELUhoqY9gv6T1tjwuFoZWKJqbTH9Bth` (cool-chiffon-stallion) all of the sums are 0.

https://testnet-api.helium.wtf/v1/validators/1ZxmSuuWfhLRum45sgk8ELUhoqY9gv6T1tjwuFoZWKJqbTH9Bth/rewards/sum
```json
{
  "meta": {
    "min_time": "2021-04-24T13:07:54Z",
    "max_time": "2021-04-24T13:07:54Z"
  },
  "data": {
    "total": 0,
    "sum": 0,
    "stddev": 0,
    "min": 0,
    "median": 0,
    "max": 0,
    "avg": 0
  }
}
```

Requesting the raw rewards returns an empty array.

https://testnet-api.helium.wtf/v1/validators/1ZxmSuuWfhLRum45sgk8ELUhoqY9gv6T1tjwuFoZWKJqbTH9Bth/rewards
```json
{
  "data": []
}
```

Am I missing something? Should I open a new issue?

**Comment by OrmEmbaar** [comment]
Oh, looking at the other rewards endpoints, it appears that I need a min and max time.

**Comment by madninja** [comment]
Exactly.. I'm adding docs for this with the following PR: https://github.com/helium/docs/pull/312

**Comment by madninja** [comment]
> Oh, looking at the other rewards endpoints, it appears that I need a min and max time.

And the reason the sum is zero is that with no parameters min_time and max_time are the same "current time" with. min_time inclusive and max_time exclusive, which means you're basically asking for the reward sum in the current minute. Not very useful, I know but it does meet the semantics (and technically could happen I guess)
