### ISSUE TITLE
Hotspot Beacon Rate

### ISSUE THREAD

**Issue by cokes518** [helium/blockchain-http#179]
For each hotspot, bucketed over time, tell me how many beacons this Hotspot was a challengee.

This should unblock the app team from launch.

Eventually we'll follow this up with whether the Beacon had witnesses and valid witnesses, and the full monty: challenge pass/fail rate.

**Comment by madninja** [comment]
I must be missing something. Isn't this exactly what https://github.com/helium/blockchain-http/pull/182 does?

**Comment by cokes518** [comment]
looks like it.

**Comment by madninja** [comment]
Re-open if you meant this to be something else @cokes518 

Duplicates #172
