### ISSUE TITLE
Hotspots should always have reward_scale field (with a default value instead of the field not being present)

### ISSUE THREAD

**Issue by danielcolinjames** [helium/blockchain-http#184]
I'm not sure what the correct default value should be, but there are some cases where a hotspot doesn't have a reward_scale value. It's probably better if the field is always there with a default value than if it sometimes doesn't show up. Either 0 or 1 would probably make sense as a default value, or possibly `null`?

The two cases I've noticed where a hotspot doesn't have the field:
- when a hotspot was just added and has started syncing, there is a brief time period where the API won't return a reward_scale field for that hotspot
- I'm not sure what causes it, but Exotic Orange Chicken seems to not have a reward scale value, even though it appears to be online and syncing: https://explorer.helium.com/hotspots/112n3pxKf1X8ZEuag81LuVust76ciGSgMjB5roxXJ8P7pN3C5GaY

**Comment by madninja** [comment]
I tested this for a hotspot that was recently added and got a `null` back:

```{
    "data": {
        "address": "112PaX1zPRE5rzKcVrXvHAm5ZY3dJa6tBQeMwBTVKMYwSem8Hkmr",
        "block": 758086,
        "block_added": 758005,
        "geocode": {
            "city_id": null,
            "long_city": null,
            "long_country": null,
            "long_state": null,
            "long_street": null,
            "short_city": null,
            "short_country": null,
            "short_state": null,
            "short_street": null
        },
        "last_change_block": 758005,
        "last_poc_challenge": null,
        "location": null,
        "name": "cheesy-spruce-wren",
        "nonce": 0,
        "owner": "13L2EcGq454yEbNp9a6kWDXuF3ycyqH3MUfimwfY5CfJMxR8Z6W",
        "reward_scale": null,
        "status": {
            "height": null,
            "listen_addrs": null,
            "online": "online"
        },
        "timestamp_added": "2021-03-13T12:20:48.000000Z"
    }
}```

I'm going to close this assuming it's fixed but please re-open if you see this again?
