### ISSUE TITLE
Additional apis related to unstaking

### ISSUE THREAD

**Issue by jdgemm** [helium/blockchain-http#189]
- ability to track unstaking when it happens
- track the amount of HNT in unbounding period

We'd look to potentially provide a graph showing how much HNT is leaving locked up system.

**Comment by madninja** [comment]
I believe this is complete now.. 

* `/v1/validators/:address` gives the current staking status of the validator
* `/v1/validators/stats` gives the number of validators and total HNT in each of the staking states (staked, cooldown)
* `/v1/accounts/:address/activity` filtered by at least the validator unstake txn would allow tracking of when the unstake happened
