### ISSUE TITLE
Missing stake_validator, transfer_stake and unstake_validator txs

### ISSUE THREAD

**Issue by pipaman** [helium/blockchain-http#194]
After postings these transactions stake_validator, transfer_stake and unstake_validator:

https://testnet-api.helium.wtf/v1/transactions/2KAbUr3VZx72gHkW1txXrY6ato_zwNpO-9nzmHtRgL0 stake_validator_v1
https://testnet-api.helium.wtf/v1/transactions/z0vG68QWOPBJEMdCtZrPrAQuHiRBCyTTOMHtQ2ZWVAQ transfer_validator_stake_v1
https://testnet-api.helium.wtf/v1/transactions/ymIOPfjZKPzmcuwjTx-Bbrb6n-azbD3b5rQ9krNv1MM unstake_validator_v1

However we found that these transactions can't be fetched using address activity https://testnet-api.helium.wtf/v1/accounts/1bRhA87goDzWGMoV17syZoK9nhtE8EjngRJ5LqE6JSsukj5Mh2M/activity?cursor=eyJibG9jayI6MTEwMCwiYW5jaG9yX2Jsb2NrIjoxMTAwfQ

**Comment by madninja** [comment]
Fixed in https://github.com/helium/blockchain-http/pull/191/commits/d4d408272d2c9a90ae58f73fa4e6ffc06ff4ff15
