### ISSUE TITLE
 API for price at time and/or block at time.

### ISSUE THREAD

**Issue by kellybyrd** [helium/blockchain-http#205]
Problem: I want to know what Oracle price was current at a given timestamp.
When thinking about this problem I came up with a couple of routes might be useful:

1) Oracle price at a given timestamp
2) Block at a given timestamp (even if #1 is implemented, this would be independently useful)

This might overlap with: https://github.com/helium/blockchain-http/issues/201, but I think it is distinct.

**Comment by madninja** [comment]
Sorry what does _block time_ at a given timestamp mean?

**Comment by kellybyrd** [comment]
Ooops! Typo. 
I just updated #2 from "block time at a given timestamp" to "block at a given timestamp". I'm imagining something that has a response just like `/blocks/:height` but instead allows the user to say: return me the block that was valid at a given UTC timestamp.
