### ISSUE TITLE
Allow getting /cities sorted by hotspot_count

### ISSUE THREAD

**Issue by danielcolinjames** [helium/blockchain-http#207]
Right now the /cities endpoint is returning cities alphabetically sorted. An option to get them sorted by hotspot_count would be awesome 😎

Not sure the best API UX, maybe `/cities?sort=hotspots` or `/cities/top` or something.

Thanks!

**Comment by danielcolinjames** [comment]
Saw @cokes518  added:
- Exclude unasserted hotspots
- Exclude offline hotspots
to [this issue](https://github.com/helium/explorer/issues/283
) which is what I want to use the route for.

I think unasserted hotspots should be fine, because they shouldn't show up in this list anyway I think, but for offline hotspots, I'm wondering if that can be added to this somehow... Maybe `total_hotspot_count` and `online_hotspot_count` 
 or `hotspot_count: { total, online }` or something like that?

**Comment by madninja** [comment]
> Saw @cokes518 added:
> 
> > * Exclude unasserted hotspots
> > * Exclude offline hotspots
> 
> to [this issue](https://github.com/helium/explorer/issues/283) which is what I want to use the route for.
> 
> I think unasserted hotspots should be fine, because they shouldn't show up in this list anyway I think, but for offline hotspots, I'm wondering if that can be added to this somehow... Maybe `total_hotspot_count` and `online_hotspot_count`
> or `hotspot_count: { total, online }` or something like that?

and the ordering would be by _total_ or by _online_?

**Comment by danielcolinjames** [comment]
@madninja good point, I realized when doing this in the hacky way in the frontend that it has to be two separate arrays because the ordering would be different, so maybe a query string e.g. exclude_offline would be the best way to do it?

**Comment by madninja** [comment]
> @madninja good point, I realized when doing this in the hacky way in the frontend that it has to be two separate arrays because the ordering would be different, so maybe a query string e.g. exclude_offline would be the best way to do it?

I'm not sure I understand what you're saying?

**Comment by danielcolinjames** [comment]
sorry for not being very clear.

I was imagining it could be done with query strings, like

/cities?sort=hotspot_count&exclude_offline=true

and then hotspot_count would represent either all hotspots if that query param wasn't there, or just online ones if it was (and that's also what they could be sorted by)

I was talking to Tim and he said they often refer to "total" numbers for marketing, so I'm going to add a toggle to the cities table to toggle exclude offline (like the coverage map has), so I would probably just hit the endpoint twice, once with exclude and once without, and then swap between the two resulting arrays

but if this isn't something that will be a useful or easy addition to the API then the way I'm calculating it now should be fine since at least it's not looping through all hotspots on the client side :)

**Comment by madninja** [comment]
an alternate proposal:

`/v1/cities?order=<ORDER>&asc=<ASC>` where `<ORDER>` is one of `online`, `offline`, `total` and the `<ASC>` parameter would allow you to sort ascending vs the default descending sort (i..e you can ommit `asc` in most cases if you just want to list from most to least)

**Comment by danielcolinjames** [comment]
love it! that's perfect
