### ISSUE TITLE
Query hotspot elevation and gain - Assert V2

### ISSUE THREAD

**Issue by tyler-whitman** [helium/blockchain-http#208]
Once we have implemented Assert Location V2 we will need a way to query for the hotspots set elevation and gain values.

I was thinking this could be added to the existing hotspots objects: https://docs.helium.com/api/blockchain/hotspots

depends on https://github.com/helium/blockchain-core/pull/519

**Comment by madninja** [comment]
Fixed by https://github.com/helium/blockchain-http/pull/230
