### ISSUE TITLE
Return `created_at` along with `hash` in the submit transaction endpoint

### ISSUE THREAD

**Issue by allenan** [helium/blockchain-http#209]
Pending transactions are keyed off of the `created_at` field rather than `hash` in order to capture repeat submitted transactions (in case an earlier one failed for reasons unrelated to the construction of the transaction). However the submit txn endpoint only returns the `hash` field at the time of submission. It would be great to also return the `created_at` field so that we can identify a specific instance of a pending transaction in the API

**Comment by madninja** [comment]
@allenan would you then not also want a specific lookup based on `created_at`? or is this all we need here

**Comment by allenan** [comment]
either way. as long as i know the created_at timestamp at creation time i can search for it in the list of pending txns matching the hash. or it could be added as a lookup option. but would it then be a combination of hash + created_at? or is it assumed that created_at is unique?

**Comment by madninja** [comment]
> either way. as long as i know the created_at timestamp at creation time i can search for it in the list of pending txns matching the hash. or it could be added as a lookup option. but would it then be a combination of hash + created_at? or is it assumed that created_at is unique?

created_at is the primary key so guaranteed to be unique... now whether iso8601 is as precise as SQL timestamps is another question so maybe we leave it like this for now

**Comment by allenan** [comment]
i know the probability of it happening would be infinitesimally small, but any concern with two pending transactions being created at exactly the same time? I guess one would succeed and one would fail
