### ISSUE TITLE
pull hotspot date filter issue

### ISSUE THREAD

**Issue by jbwgames** [helium/blockchain-http#234]
using C# in Visual Studio 2017 Pro:
Client rewards = new Client(new NewtonsoftSerializationAdapter(), new Uri($"{APICalls.uri}hotspots/{HotSpotURI}/rewards/sum?max_time={maxValueInfo}&min_time={minValueInfo}"));
When passing max_time can only pass date, same with min_time, if i try to pass time value, error happens:
Example: max_time = "2021-04-19T23:59:59Z"
Example: min_time = "2021-04-19T00:00:00Z"
Full URL:
https://api.helium.io/v1/hotspots/11kQt8CFvaSCRcBxWtnC6FAaNU1f17cfYdbH7DqckVASzXUWu9Z/rewards/sum?max_time=21-04-19T23:59:59Z&min_time=2021-04-19T00:00:00Z

Results:
{"error":"Bad Request"}

Expected Results:
Data based on range within time, else if no time, then make max_time INCLUSIVE not EXCLUSIVE.
Right now, max_time is exclusive and since ommitting the time the end result is midnight of that day, as in AM, not PM, so the above would result in zero records if slated:

Example: max_time = "2021-04-19T23:59:59Z"
Example: min_time = "2021-04-19T00:00:00Z"
Full URL:
https://api.helium.io/v1/hotspots/11kQt8CFvaSCRcBxWtnC6FAaNU1f17cfYdbH7DqckVASzXUWu9Z/rewards/sum?max_time=21-04-19&min_time=2021-04-19

Where as it should be the results of that day, to pull the 19th in the above example, it must currently be
https://api.helium.io/v1/hotspots/11kQt8CFvaSCRcBxWtnC6FAaNU1f17cfYdbH7DqckVASzXUWu9Z/rewards/sum?max_time=21-04-20&min_time=2021-04-19

**Comment by madninja** [comment]
I must've not been paying attention while we were chatting in Discord and failed to notice that you while your `Example:` text is right your actual URL is wrong:

```https://api.helium.io/v1/hotspots/11kQt8CFvaSCRcBxWtnC6FAaNU1f17cfYdbH7DqckVASzXUWu9Z/rewards/sum?max_time=21-04-19T23:59:59Z&min_time=2021-04-19T00:00:00Z```

Note how max_time starts with `21` instead of 2021

using a fully qualified year: 

```
http --body get https://api.helium.io/v1/hotspots/11kQt8CFvaSCRcBxWtnC6FAaNU1f17cfYdbH7DqckVASzXUWu9Z/rewards/sum\?max_time=2021-04-19T23:59:59Z\&min_time=2021-04-19T00:00:00Z
{
    "data": {
        "avg": 0.020832006666666666,
        "max": 0.0,
        "median": 7.6e-07,
        "min": 0.0,
        "stddev": 0.031309020674,
        "sum": 18748806,
        "total": 0.18748806
    },
    "meta": {
        "max_time": "2021-04-19T23:59:59Z",
        "min_time": "2021-04-19T00:00:00Z"
    }
}
```
