### ISSUE TITLE
Specify starting block

### ISSUE THREAD

**Issue by davetapley** [helium/blockchain-http#237]
I'd like to be able to link to a specific block/blocks in https://api.helium.io/v1/oracle/prices on #238, but I don't think there's any way to do that currently, because the pages are moving around as new blocks come in.

Could a `?block=` param be added which would start pagination at that block?

---

Originally request (based on my misunderstanding of `cursor`):
~I want to create an absolute link to what is **currently** the first page returned by https://api.helium.io/v1/oracle/prices, 
but I don't know what cursor to pass to `?cursor=` because only the previous page's cursor is given.~

**Comment by madninja** [comment]
Sorry, I don't know what this request means.. There is no "currently first page". Oracle prices are returned from the latest block down towards genesis.

**Comment by davetapley** [comment]
Ah, I may have misunderstood how `cursor` works:

I was under the impression that if I `GET https://api.helium.io/v1/oracle/prices?cursor=foo` then I would **always** get the same response body (for `foo`), is that not true?

**Comment by madninja** [comment]
> Ah, I may have misunderstood how `cursor` works:
> 
> I was under the impression that if I `GET https://api.helium.io/v1/oracle/prices?cursor=foo` then I would **always** get the same response body (for `foo`), is that not true?

that is correct... but the _first_ page can't be that since that page is always growing as blocks come in.. once you get the first page back you have a cursor for the next page where you know all the facts

**Comment by davetapley** [comment]
Gotcha, I've updated the issue title/description with what I actually wanted. Thanks.

**Comment by madninja** [comment]
> Gotcha, I've updated the issue title/description with what I actually wanted. Thanks.

can you explain what you're trying to get out of this? Oracle price at a specific height or an actual list starting at a given block, if so why?

**Comment by davetapley** [comment]
A list starting at a given block, so I can use it in the link on #238, without the relevant blocks eventually drifting off the first page.

**Comment by madninja** [comment]
> A list starting at a given block, so I can use it in the link on #238, without the relevant blocks eventually drifting off the first page.

Understood.. adding this makes edge caches miss more often which is why I'v shied away from them so far for most of the APIs. There may be a way to do this now though.
