### ISSUE TITLE
Oracle price appears stuck for 12 hours on night of April 18th

### ISSUE THREAD

**Issue by davetapley** [helium/blockchain-http#238]
If you look here :arrow_down:  you can see a new price reliably every 10 blocks, except between `810050` and `810800`.
https://api.helium.io/v1/oracle/prices (blocks might not be on first page when you're reading this, see https://github.com/helium/blockchain-http/issues/237).

---

Not sure if by design, but it looks very suspiciously like it's broken, especially on https://explorer.helium.com/market:

![image](https://user-images.githubusercontent.com/48232/115429199-0aab8780-a1b8-11eb-8042-69bd5e1ca480.png)

**Comment by jamiew** [comment]
@davetapley unfortunately this is a result of <5 oracles voting during these periods, and it is not an uncommon occurance. Here is a detailed dashboard: https://etl.dewi.org/public/dashboard/377b53e9-d4ed-48f0-9352-9285ad56461e

As you can see here are several extended periods with only a few oracles voting: 

![](https://dl.dropboxusercontent.com/s%2Fa182y6upx8h200z%2Fimage_rvkkk0ubaz.png)

SHAME!
SHAME!
SHAME!

And thus also not a blockchain-http issue

**Comment by abhay** [comment]
Closing issue since it's not an HTTP problem. But frustrating.
