### ISSUE TITLE
Oracle Prices Stats endpoint doesn't work in prod

### ISSUE THREAD

**Issue by kellybyrd** [helium/blockchain-http#248]
Just tried the example at `https://docs.helium.com/api/blockchain/oracle-prices#oracle-price-stats`
Doing `https://api.helium.io/v1/oracle/prices/stats?min_time=-30%20day`  in either a browser or with curl  gives me:
```
{
"error": "Bad Request"
}
```

It tried various combinations of min_time and max_time and have not found one that works. As an example, this fails in the same way:
`http://api.helium.io/v1/oracle/prices/stats?min_time=2021-04-25T00:00:00Z&max_time_min_time=2021-04-27T00:00:00Z`

**Comment by madninja** [comment]
Fixed  with the deploy 1.2.85

**Comment by kellybyrd** [comment]
Confirmed. Works for me now. Thanks!
