### ISSUE TITLE
Incorrectly reported transaction failures

### ISSUE THREAD

**Issue by tyler-whitman** [helium/blockchain-http#251]
There are some community issues being reported where users are seeing failure notifications for assert v2 transactions that seem to have actually cleared successfully in the blockchain. It seems some pending transactions are reporting a failed state, but the transactions are in fact clearing.

This pending txn claims a failure: https://api.helium.io/v1/pending_transactions/MAGOywg2lQuUWuo7jetRAVnPYcIo1JChXbvFM0mYUO0
But the txn was successful: https://api.helium.io/v1/transactions/MAGOywg2lQuUWuo7jetRAVnPYcIo1JChXbvFM0mYUO0

As well as https://github.com/helium/hotspot-app/issues/530 seems related to the same problem, there isn't a hotspot id but you can see the app is reporting failures but the transaction is showing up on explorer.

**Comment by madninja** [comment]
This may have been fixed with etl disabling the gateway cache which would give wildly wrong results back
