### ISSUE TITLE
/hexes/:h3_index API route

### ISSUE THREAD

**Issue by allenan** [helium/blockchain-http#255]
as we shift towards a hexagonal representation of hotspots, hexes will become a more top-level UI component. Accordingly, we'll need to be able to look up the hotspots contained within a hexagon, specifically a res8 hexagon.

The API route may look something like:

```
https://api.helium.io/v1/hexes/:h3_index
```

where `:h3_index` is a res8 h3 index and would return a cursor-paginated list of hotspots within that hex.

We discussed an implementation that involves creating a new `location_hex` or similarly named column that is internal to the API and stores the truncated location index. This would be used for searching as a first step, and as a second step could be used to replace the `location` field in API queries as we transition towards representing everything at res8.

**Comment by madninja** [comment]
@allenan slightly modified proposal to follow the url conventions for hotspot lookups (e.g. `/v1/hotspots/name/:name`)

`/v1/hotspots/hex/:h3_index` to look up all hotspots that have that h3 index.. only res8 indexes will be supported and the endpoint will report a invalid request for non res8 hex lookup requests.
