### ISSUE TITLE
Duplicate HS when requesting hotspots/location/distance & cursors

### ISSUE THREAD

**Issue by snip** [helium/blockchain-http#257]
When i try to get all HS around a given point using a big distance (so using cursors due to number of points in this area), i get lot of hotspots duplicates.

Example:
Trying this: https://api.helium.io/v1/hotspots/location/distance?lat=46.89691296386259&lon=2.605102080842385&distance=900000
follow each cursors, and as an example i get 4 entries related to dazzling-pewter-lark

Is it something expected?

Thanks

**Comment by madninja** [comment]
@snip this was deployed to the api. Could you verify it works as expected?
