### ISSUE TITLE
Testnet API Issue

### ISSUE THREAD

**Issue by anthonyra** [helium/blockchain-http#274]
Any validator that is added after # 598 is resulting in their "online status" being null. 

Example,
https://testnet-api.helium.wtf/v1/validators/1Zj4ehyXPyfuSwNV9RCaTT2R79qg41592tXV19Veu3bK2Qsb7dz

Results,
`"status":{"online":null,"listen_addrs":null,"height":null}`

**Comment by madninja** [comment]
This seems to be clearing slowly after a testnet-etl bounce
