### ISSUE TITLE
Display Data Credits Spent (last 30 days)

### ISSUE THREAD

**Issue by woodlandsquash** [helium/blockchain-http#282]
There is currently no simple way to isolate the data credits spent in the last 30 days on New hotspot and location asserts vs Data Transfer.

This would be an incredibly helpful statistic for the community to be able to understand the market growth of network usage. Currently it would be a several step process (downloading CSV’s per manufacturer) to figure out this number. Although hotspot and location asserts will always be a portion of Data Credits burned they currently represent a disproportionally large percentage compared to where they will likely be in the future, so it makes it difficult to really understand the network’s usage growth based on the last 30 Days Data Credits used.

P.S. I filed this request on the “Explorer” front end and I was told to file it here instead.

**Comment by madninja** [comment]
so this: 

```
 http --body get https://api.helium.io/v1/dc_burns/stats
{
    "data": {
        "last_day": {
            "add_gateway": 3415000000,
            "assert_location": 1336500000,
            "fee": 228365000,
            "state_channel": 1506530,
            "total": 4981371530
        },
        "last_month": {
            "add_gateway": 119513000000,
            "assert_location": 42302500000,
            "fee": 7686160000,
            "oui": 330000000,
            "state_channel": 55737656,
            "total": 169887397656
        },
        "last_week": {
            "add_gateway": 22805000000,
            "assert_location": 9302500000,
            "fee": 1628665000,
            "state_channel": 12381816,
            "total": 33748546816
        }
    },
    "meta": {
        "timestamp": "2021-07-23T01:19:04Z"
    }
}
```
is not you want?

**Comment by madninja** [comment]
@woodlandsquash I'm going to close this under the assumption the above works. Please re-open if you meant something else
