### ISSUE TITLE
add more data-only hotspot data to api

### ISSUE THREAD

**Issue by cokes518** [helium/blockchain-http#290]
* add `count` of data-only Hotspots
   * right now, we only show a count of all hotspots on chain, it'd be nice to show the subset of those that are data-only or light/full. 
   * food for thought: is it worth adding a hotspots/stats, like there is for validator/stats?
* generate paginated list of data-only hotspots for explorer map filter
  * the explorer team would like to plot data-only hotspots on a map, and so we'll need a paginated list of these hotspots

note to marc: lower priority, should be looked at after finishing "inverse of witness list" request.

**Comment by madninja** [comment]
Fixed by #295

**Comment by madninja** [comment]
@cokes518 Likely yes on stats, but less put a different issue in for it when we actually need it?
