### ISSUE TITLE
Hotspot activity endpoint often fails with '503 first byte timeout' error

### ISSUE THREAD

**Issue by Bogardo** [helium/blockchain-http#311]
Request

```
GET https://api.helium.io/v1/hotspots/:address/activity[?cursor=:cursor]
```

Response
```
Error 503 first byte timeout
first byte timeout

Guru Mediation:
Details: cache-ams21021-AMS 1627913996 982677660
```

---

The hotspot activity endpoint has been very unreliable for me since somewhere around 2021-07-23.
Requests often time out with a `503 first byte timeout' error or take a very long time to complete.

This impacts not only the API itself but also the explorer, and I assume the app as well.

There has already been some discussion about this issue on Discord in the `#blockchain-development` channel, but I realized no bug report was created yet. It was suggested to possibly add new indexes to the database, but further research was required. 

There is an [open issue](https://github.com/helium/blockchain-http/issues/289) with a feature request to add optional `min_time` and `max_time` parameters to the `hotspots/:address/activity/count` endpoint.
If such a change would improve performance on the `activity` endpoint as well, then that would be a welcome change too.

**Comment by LilaQ** [comment]
Experiencing the same issues, which is affecting iOS app, OSX widget & discord bot.
