### ISSUE TITLE
Add /cities/:cityid route

### ISSUE THREAD

**Issue by danielcolinjames** [helium/blockchain-http#312]
I'm hoping it would be an easy add to get the info that shows up for this request:

https://api.helium.io/v1/cities?search=toronto

```json
{
  "data": [
    {
      "short_state": "ON",
      "short_country": "CA",
      "short_city": "Toronto",
      "online_count": 956,
      "offline_count": "166",
      "long_state": "Ontario",
      "long_country": "Canada",
      "long_city": "Toronto",
      "hotspot_count": "1122",
      "city_id": "dG9yb250b29udGFyaW9jYW5hZGE"
    }
  ]
}
```

to show up for a specific city ID (rather than a search term), something like:

https://api.helium.io/v1/cities/dG9yb250b29udGFyaW9jYW5hZGE

(and also maybe all the "count" fields could all show up as integers instead of strings, to keep things consistent)

The use case I'm thinking of is a view in Explorer for each city, where it could show some of the basic statistics of the city when you navigate to that route. But right now, there's no easy way to get the info above ^ from the API for a given city ID (when a user navigates directly to explorer.helium.com/hotspots/cities/:cityid)

**Comment by madninja** [comment]
Done in #323
