### ISSUE TITLE
Pending transactions not showing correctly the cleared status.

### ISSUE THREAD

**Issue by andreiguzga** [helium/blockchain-http#324]
For the last two days I've seen several transactions which in the pending_transactions endpoint show as failed with invalid,bad_nonce but the transaction actually got through.

Example: 
https://api.helium.io/v1/pending_transactions/PxePgosiYg0YZ-j0b_wO83iB0ikMdrD_9Tj7VKLv8w4
https://api.helium.io/v1/transactions/PxePgosiYg0YZ-j0b_wO83iB0ikMdrD_9Tj7VKLv8w4

**Comment by madninja** [comment]
This is a bug that we've been working to expose for some time. 

To help debug: Are you firing of multiple payments after each other and then see this happen to one or more?

**Comment by andreiguzga** [comment]
Well it depends. For this case no. As I manage a staking platform there are multiple transactions happening some times. But for these last transactions they were isolated and they were far apart. I started noticing these errors when the API is responding slow. I've also had some Blockchain timeout requests.

I am using the helium-js library to do the transactions.  When doing the payment we are incrementing the nonce like this nonce: payer.speculativeNonce + 1.

Is it possible that the problem may be that if the API is slow,  the speculativeNonce is not updated and we are receiving the old nonce?

For example, if a wallet does two consecutive payments (which in our case it can be, as our customers need to transfer HNT to an internal wallet and after that stake by transferring from that internal wallet to our main wallet) on the second transfer we don't get the updated nonce and it is triggering this error.

**Comment by andreiguzga** [comment]
I just remembered that yesterday when we did repay some unstakes I had 6 transactions with this status. Those transactions were indeed triggered one after each other relatively quickly (1-5 seconds apart) . You can see below the times when we got the errors.

  Aug 13, 2021, 01:40:33: AM UTC
Blockchain timeout
Transaction failed
  Aug 13, 2021, 01:40:33: AM UTC
Blockchain timeout
Transaction failed
  Aug 13, 2021, 01:40:32: AM UTC
Blockchain timeout
Transaction failed
  Aug 13, 2021, 01:40:27: AM UTC
Blockchain timeout
Transaction failed
  Aug 13, 2021, 01:40:27: AM UTC
Blockchain timeout
Transaction failed
  Aug 13, 2021, 01:40:22: AM UTC
Blockchain timeout
Transaction failed

Transaction example
https://api.helium.io/v1/pending_transactions/q_OuMbrcqq9JTfgDshc6hSvLSQzoIzklK-jVdjxQNtc
https://api.helium.io/v1/transactions/q_OuMbrcqq9JTfgDshc6hSvLSQzoIzklK-jVdjxQNtc

Don't think these are related to the issue from above as these failed with the status of undecided_timeout. But the problem is somewhat the same as I don't have a cleared status in the pending transaction.

**Comment by madninja** [comment]
There's another one with 

> Well it depends. For this case no. As I manage a staking platform there are multiple transactions happening some times. But for these last transactions they were isolated and they were far apart. I started noticing these errors when the API is responding slow. I've also had some Blockchain timeout requests.
> 
> I am using the helium-js library to do the transactions. When doing the payment we are incrementing the nonce like this nonce: payer.speculativeNonce + 1.
> 
> Is it possible that the problem may be that if the API is slow, the speculativeNonce is not updated and we are receiving the old nonce?

Yes.. and that's why you have to use payment_v2 to issue multiple payments in one shot to avoid this exact problem.. Alternately you will have to update the nonce yourself as you construct txns. I'd highly recommend using payment_v2 to issue payments

> 
> For example, if a wallet does two consecutive payments (which in our case it can be, as our customers need to transfer HNT to an internal wallet and after that stake by transferring from that internal wallet to our main wallet) on the second transfer we don't get the updated nonce and it is triggering this error.

The undecided timeout appears to be a good example of the issue we're hunting down: 

https://api.helium.io/v1/pending_transactions/HFUxCgiZxnGwYG-UIfw3ZsSfMJG4eDUddAkjM85frHk 

is another example of this which failed but then succeeded on chain too

**Comment by BenoitDuffez** [comment]
I had a similar behavior with an add_gateway that went through (e.g. gateway successfully added to the blockchain) but didn't show up as cleared in the pending transactions list (instead: `rejected` for add_gateway and `unknown_gateway` for assert_location_v2).  
Gateway = `112e3EMDd3ZACotVtkvSf7aiZwh3nyAHdVN3jXYYfLmwxBJXu95J`

Let me know if you need further details.

**Comment by Misca** [comment]
Just managed to reproduce this kind of error: "{invalid,bad_nonce}" - for this transaction: https://explorer.helium.com/txns/mFERzpncty5ekZ3VLth3bJM5QQCxoivBY2Fc8N2_wu0
So far the transaction did not go trough and did not revert (waiting to see which of the two will happen)

**Comment by madninja** [comment]
> Just managed to reproduce this kind of error: "{invalid,bad_nonce}" - for this transaction: https://explorer.helium.com/txns/mFERzpncty5ekZ3VLth3bJM5QQCxoivBY2Fc8N2_wu0
> So far the transaction did not go trough and did not revert (waiting to see which of the two will happen) - as in the tokens are not displayed in either my helium wallet, nor the my other wallet (crypto.com)

This transaction did clear as your link shows.. the chain contains the truth. The pending transaction output can be incorrect, especially across the chain halt or outages.
