### ISSUE TITLE
2021-09-15T00:00:59.999Z is returned as 2021-09-15T00:00:60Z 

### ISSUE THREAD

**Issue by pantyporowicz** [helium/blockchain-http#336]
Hi,
I found isssue with date, when I provided to API some date with 59 seconds and 999 ms, then API returns date with 60 seconds. 

1 .Current behavior: 
- Provided date: 2021-09-15T00:00:59.999Z, API returns  2021-09-15T00:00:60Z,

2. Exceted behavior:
- Provided date: 2021-09-15T00:00:59.999Z, API returns 2021-09-15T00:00:59Z,

![image](https://user-images.githubusercontent.com/78741013/133768606-e6017aef-f3dc-4fd9-83bf-41b1703be949.png)

**Comment by madninja** [comment]
So you expect the seconds to be rounded up instead of truncated? That's apparently not quite how Postgres parses ISO8601 though
