### ISSUE TITLE
DB connect error

### ISSUE THREAD

**Issue by appop** [helium/blockchain-http#352]
1:58:06.967 [error] CRASH REPORT Process <0.828.0> with 0 neighbours crashed with reason: no match of right hand value {error,"Missing DATABASE_URL.~n"} in bh_sup:pool_opts/1line 73
11:58:06.967 [error] CRASH REPORT Process <0.826.0> with 0 neighbours exited with reason: {{{badmatch,{error,"Missing DATABASE_URL.~n"}},[{bh_sup,pool_opts,1,[{file,"/app/src/bh_sup.erl"},{line,73}]},{bh_sup,'-init/1-fun-0-',1,[{file,"/app/src/bh_sup.erl"},{line,41}]},{lists,foreach,2,[{file,"lists.erl"},{line,1342}]},{bh_sup,init,1,[{file,"/app/src/bh_sup.erl"},{line,39}]},{supervisor,init,1,[{file,"supervisor.erl"},{line,301}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,417}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,385}]},{proc_lib,init_p_do_apply,3,[{...},...]}]},...} in application_master:init/4 line 138
11:58:06.968 [info] Application blockchain_http exited with reason: {{{badmatch,{error,"Missing DATABASE_URL.~n"}},[{bh_sup,pool_opts,1,[{file,"/app/src/bh_sup.erl"},{line,73}]},{bh_sup,'-init/1-fun-0-',1,[{file,"/app/src/bh_sup.erl"},{line,41}]},{lists,foreach,2,[{file,"lists.erl"},{line,1342}]},{bh_sup,init,1,[{file,"/app/src/bh_sup.erl"},{line,39}]},{supervisor,init,1,[{file,"supervisor.erl"},{line,301}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,417}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,385}]},{proc_lib,init_p_do_apply,3,[{...},...]}]},...}
{"Kernel pid terminated",application_controller,"{application_start_failure,blockchain_http,{{{badmatch,{error,\"Missing DATABASE_URL.~n\"}},[{bh_sup,pool_opts,1,[{file,\"/app/src/bh_sup.erl\"},{line,73}]},{bh_sup,'-init/1-fun-0-',1,[{file,\"/app/src/bh_sup.erl\"},{line,41}]},{lists,foreach,2,[{file,\"lists.erl\"},{line,1342}]},{bh_sup,init,1,[{file,\"/app/src/bh_sup.erl\"},{line,39}]},{supervisor,init,1,[{file,\"supervisor.erl\"},{line,301}]},{gen_server,init_it,2,[{file,\"gen_server.erl\"},{line,417}]},{gen_server,init_it,6,[{file,\"gen_server.erl\"},{line,385}]},{proc_lib,init_p_do_apply,3,[{file,\"proc_lib.erl\"},{line,226}]}]},{blockchain_http_app,start,[normal,[]]}}}"}
Kernel pid terminated (application_controller) ({application_start_failure,blockchain_http,{{{badmatch,{error,"Missing DATABASE_URL.~n"}},[{bh_sup,pool_opts,1,[{file,"/app/src/bh_sup.erl"},{line,73}]}

Crash dump is being written to: erl_crash.dump...done

I already add my db config in .env
I use  docker build -t helium/http . create my docker image.
Start command

docker run -d \
--restart always \
--publish 8080:8080/tcp \
--name etl_http \
-e DATABASE_URL=postgresql://xxxx:xxxx@xxxx:5432/helium_blockchain \
helium/http:latest

Could help on this?

**Comment by madninja** [comment]
Try putting the DATABASE_URL=... in an actual `.env` file and mounting it in the docker image?

**Comment by appop** [comment]
I  added this to to .env file, but which path I need to mount?

**Comment by madninja** [comment]
Oh I see what you did wrong here.. Look at .env.template.. You're setting the wrong environment variables in your `-e` option

**Comment by appop** [comment]
I copy .env.template to .env, then I got  an error, so I added this configuration, If I want to use .env, how did I add this to the docker image？

**Comment by madninja** [comment]
> I copy .env.template to .env, then I got an error, so I added this configuration, If I want to use .env, how did I add this to the docker image？

No, please look in the template file and set your environment variables in your docker run command to have the right names

**Comment by appop** [comment]
@madninja Thanks, with you advice we finally solved this.
