### ISSUE TITLE
Cursor loop

### ISSUE THREAD

**Issue by nikolakurtic** [helium/blockchain-http#353]
From time to time I get cursor loop in hotspots endpoint response, eg
`https://helium-api.stakejoy.com/v1/hotspots?cursor=eyJoZWlnaHQiOjEwOTI2NDksImZpbHRlcl9tb2RlcyI6WyJmdWxsIiwibGlnaHQiLCJkYXRhb25seSJdLCJiZWZvcmVfYmxvY2siOjEwOTIxNTMsImJlZm9yZV9hZGRyZXNzIjoiMTEyNmNCb3hBVnVuN3Q4akh3Z2k4d3h3Y0J4Z3JvTjFtSjJXTEp3OUJHNDNjaVBUZ2poTCJ9 `
, there's the same cursor in response.

response
`{"data":[...],"cursor":"eyJoZWlnaHQiOjEwOTI4OTksImZpbHRlcl9tb2RlcyI6WyJmdWxsIiwibGlnaHQiLCJkYXRhb25seSJdLCJiZWZvcmVfYmxvY2siOjEwOTE4NzQsImJlZm9yZV9hZGRyZXNzIjoiMTFuZ1N0VHJxMVpaeGF3OThORll5Z1BNM3ZVb2ZmOVo4NjdQZGdWZUhTTnJlV3lvdUNWIn0"}`

**Comment by nikolakurtic** [comment]
This also happens with loc_assertion endpoint.

**Comment by andreiguzga** [comment]
From what I can see in the response it's not the same cursor. The beginning of the cursor looks the same but it is in fact not. Compare the cursor in a file editor or something and you will see that sometimes there are just small differences between cursors.

**Comment by nikolakurtic** [comment]
Yej, but I get the same set of data, and it goes forever.

**Comment by andreiguzga** [comment]
I've tested now those two cursors and it doesn't seem to give me the same data. On the second request are you replacing the cursor with the cursor from the first request response? Might be a silly question.

**Comment by nikolakurtic** [comment]
Of course, I have been running the same code for months, this happens let's say once in 3 days.

**Comment by andreiguzga** [comment]
I've tested this in postman and below are the results. Clearly it is something that is happening randomly as when I tried it it worked.

First request with cursor `eyJoZWlnaHQiOjEwOTI2NDksImZpbHRlcl9tb2RlcyI6WyJmdWxsIiwibGlnaHQiLCJkYXRhb25seSJdLCJiZWZvcmVfYmxvY2siOjEwOTIxNTMsImJlZm9yZV9hZGRyZXNzIjoiMTEyNmNCb3hBVnVuN3Q4akh3Z2k4d3h3Y0J4Z3JvTjFtSjJXTEp3OUJHNDNjaVBUZ2poTCJ9`

Response starts with
`{
            "lng": -118.41846100110146,
            "lat": 34.01254317356683,
            "timestamp_added": "2021-11-10T02:55:24.000000Z",
            "status": {
                "timestamp": "2021-11-19T21:53:33.132000Z",
                "online": "online",
                "listen_addrs": [
                    "/p2p/112aSa8zAyBBVfMZHxiiEmVVafPMit1SA9okroeH8NSfsN3cEuS8/p2p-circuit/p2p/112f9jjvJtoUG2q8szP1oeChwhB6zZPFm8vFx58opZRTgAhAMpBL"
                ],
                "height": 1104267
            },
            "reward_scale": 0.14471435546875,
            "payer": "14sKWeeYWQWrBSnLGq79uRQqZyw3Ldi7oBdxbF6a54QboTNBXDL",
            "owner": "14bXfgtW4LrmMMZRZ4KQaaZPq7pddYBBFqmrAciibnVfJYbeTYJ",
            "nonce": 1,
            "name": "real-rusty-wolf",
            "mode": "full",
            "location_hex": "8829a19863fffff",
            "location": "8c29a19862891ff",
            "last_poc_challenge": 1105014,
            "last_change_block": 1105242,
            "geocode": {
                "short_street": "Tuller Ave",
                "short_state": "CA",
                "short_country": "US",
                "short_city": "Los Angeles",
                "long_street": "Tuller Avenue",
                "long_state": "California",
                "long_country": "United States",
                "long_city": "Los Angeles",
                "city_id": "bG9zIGFuZ2VsZXNjYWxpZm9ybmlhdW5pdGVkIHN0YXRlcw"
            },
            "gain": 40,
            "elevation": 2,
            "block_added": 1092153,
            "block": 1105319,
            "address": "112f9jjvJtoUG2q8szP1oeChwhB6zZPFm8vFx58opZRTgAhAMpBL"
        }`

And cursor is `eyJoZWlnaHQiOjExMDUzMTksImZpbHRlcl9tb2RlcyI6WyJmdWxsIiwibGlnaHQiLCJkYXRhb25seSJdLCJiZWZvcmVfYmxvY2siOjEwOTE4NzQsImJlZm9yZV9hZGRyZXNzIjoiMTFuZ1N0VHJxMVpaeGF3OThORll5Z1BNM3ZVb2ZmOVo4NjdQZGdWZUhTTnJlV3lvdUNWIn0`

Second request using the above cursor: `eyJoZWlnaHQiOjExMDUzMTksImZpbHRlcl9tb2RlcyI6WyJmdWxsIiwibGlnaHQiLCJkYXRhb25seSJdLCJiZWZvcmVfYmxvY2siOjEwOTE4NzQsImJlZm9yZV9hZGRyZXNzIjoiMTFuZ1N0VHJxMVpaeGF3OThORll5Z1BNM3ZVb2ZmOVo4NjdQZGdWZUhTTnJlV3lvdUNWIn0`

Response starts with
`{
            "lng": -80.06557516327354,
            "lat": 26.514965746646382,
            "timestamp_added": "2021-11-09T22:46:43.000000Z",
            "status": {
                "timestamp": "2021-11-17T13:26:27.981000Z",
                "online": "online",
                "listen_addrs": [
                    "/p2p/112Czo1ufE6J352dyCkkYKN67wjBPeK3VrNG2JxyXXwJVhGASmcG/p2p-circuit/p2p/11nnsAj3Q8G3TYG1zqU4mpP5DqF8yd3zWgi6DtUoi89qre75EkM"
                ],
                "height": 1100664
            },
            "reward_scale": 1.0,
            "payer": "14h2zf1gEr9NmvDb2U53qucLN2jLrKU1ECBoxGnSnQ6tiT6V2kM",
            "owner": "13GHvgsHj9wnFb9hT1tgiP5fWtnXRjGBnSZFrq2CMPkzx3mUyft",
            "nonce": 1,
            "name": "brief-sable-toad",
            "mode": "full",
            "location_hex": "8844ae9191fffff",
            "location": "8c44ae9190759ff",
            "last_poc_challenge": 1105041,
            "last_change_block": 1105242,
            "geocode": {
                "short_street": "Woolbright Rd",
                "short_state": "FL",
                "short_country": "US",
                "short_city": "Boynton Beach",
                "long_street": "Woolbright Road",
                "long_state": "Florida",
                "long_country": "United States",
                "long_city": "Boynton Beach",
                "city_id": "Ym95bnRvbiBiZWFjaGZsb3JpZGF1bml0ZWQgc3RhdGVz"
            },
            "gain": 23,
            "elevation": 5,
            "block_added": 1091874,
            "block": 1105321,
            "address": "11nnsAj3Q8G3TYG1zqU4mpP5DqF8yd3zWgi6DtUoi89qre75EkM"
        },`

**Comment by madninja** [comment]
Yeah, I've been trying to reproduce this as well to no avail so far.

**Comment by nikolakurtic** [comment]
I also cannot reproduce it anymore. I guess this can be closed.
