### ISSUE TITLE
Different longitude variable names

### ISSUE THREAD

**Issue by alex-bellon** [helium/blockchain-http#368]
In the response for `api.helium.io/v1/hotspots/location/distance`, `api.helium.io/v1/hotspots/:address`, etc. the longitude variable is named `lng`, but in the request for `api.helium.io/v1/hotspots/location/distance` it uses the variable name `lon`. 

Maybe the request for `api.helium.io/v1/hotspots/location/distance` could also support `lng` as not to break anything.

**Comment by madninja** [comment]
Definitely annoying that we missed that naming inconsistency. Is this request for a fix just for consistency reasons or do you have a specific library/use in mind that relies on the name being the same? If the former I'd rather not add more logic

**Comment by alex-bellon** [comment]
The request was for consistency, I had just come across the discrepancy when writing a script that was using the API and was getting errors when I tried using `lng`. I understand not wanting to add more logic though so feel free to close the issue.
