### ISSUE TITLE
What are the minimum requirements? Add to README

### ISSUE THREAD

**Issue by HeliumMonitor** [helium/blockchain-http#372]
What are the minimum system requirements (approximately) to run this server? What additional disk space is used? Is it very RAM intensive? Can it be run on a cheap VPS, as long as there is low request load?

**Comment by madninja** [comment]
The http workers have low requirements. They rely on being connected to a database, but otherwise consume basically no resources.

**Comment by HeliumMonitor** [comment]
Does this require a full copy of the blockchain? If so, how big is the blockchain?

**Comment by madninja** [comment]
> Does this require a full copy of the blockchain? If so, how big is the blockchain?

yes it does.. which is served out of Postgres and filled in by [blockchain-etl](https://github.com/helium/blockchain-etl)
