### ISSUE TITLE
/v1/accounts/:address/activity leads to 500 internal server error

### ISSUE THREAD

**Issue by jshprentz** [helium/blockchain-http#385]
### Summary

Retrieving recent account activity from the Helium Blockchain API fails with HTTP status code 500: internal server error. For example, the first request returned only a cursor and the second request using that cursor failed.

```
2021-12-20 08:12:57,307 - DEBUG - urllib3.connectionpool - Starting new HTTPS connection (1): api.helium.io:443
2021-12-20 08:12:57,479 - DEBUG - urllib3.connectionpool - https://api.helium.io:443 "GET /v1/accounts/13S5YTPiKEqqR9G8AAwK5rfwKexQ756kZxBUvtzFLxQW4adZ9S7/activity HTTP/1.1" 200 529
2021-12-20 08:13:46,368 - DEBUG - urllib3.connectionpool - https://api.helium.io:443 "GET /v1/accounts/13S5YTPiKEqqR9G8AAwK5rfwKexQ756kZxBUvtzFLxQW4adZ9S7/activity?cursor=eyJ0eXBlcyI6WyJjb2luYmFzZV92MSIsInNlY3VyaXR5X2NvaW5iYXNlX3YxIiwib3VpX3YxIiwic3RhdGVfY2hhbm5lbF9vcGVuX3YxIiwic3RhdGVfY2hhbm5lbF9jbG9zZV92MSIsImdlbl9nYXRld2F5X3YxIiwicm91dGluZ192MSIsInBheW1lbnRfdjEiLCJzZWN1cml0eV9leGNoYW5nZV92MSIsImNvbnNlbnN1c19ncm91cF92MSIsImFkZF9nYXRld2F5X3YxIiwiYXNzZXJ0X2xvY2F0aW9uX3YxIiwiYXNzZXJ0X2xvY2F0aW9uX3YyIiwiY3JlYXRlX2h0bGNfdjEiLCJyZWRlZW1faHRsY192MSIsInBvY19yZXF1ZXN0X3YxIiwicG9jX3JlY2VpcHRzX3YxIiwidmFyc192MSIsInJld2FyZHNfdjEiLCJyZXdhcmRzX3YyIiwidG9rZW5fYnVybl92MSIsImRjX2NvaW5iYXNlX3YxIiwidG9rZW5fYnVybl9leGNoYW5nZV9yYXRlX3YxIiwicGF5bWVudF92MiIsInByaWNlX29yYWNsZV92MSIsInRyYW5zZmVyX2hvdHNwb3RfdjEiLCJ0cmFuc2Zlcl9ob3RzcG90X3YyIiwic3Rha2VfdmFsaWRhdG9yX3YxIiwidW5zdGFrZV92YWxpZGF0b3JfdjEiLCJ0cmFuc2Zlcl92YWxpZGF0b3Jfc3Rha2VfdjEiLCJ2YWxpZGF0b3JfaGVhcnRiZWF0X3YxIiwiY29uc2Vuc3VzX2dyb3VwX2ZhaWx1cmVfdjEiXSwibWluX2Jsb2NrIjo0NzQzMjUsIm1heF9ibG9jayI6MTE0NzEzNiwiYmxvY2siOjExNDcxMDAsImFuY2hvcl9ibG9jayI6MTE0NzEwMH0 HTTP/1.1" 500 21
2021-12-20 08:13:46,369 - INFO - HeliumApiError - Unexpected HTTP response
< GET /v1/accounts/13S5YTPiKEqqR9G8AAwK5rfwKexQ756kZxBUvtzFLxQW4adZ9S7/activity?cursor=eyJ0eXBlcyI6WyJjb2luYmFzZV92MSIsInNlY3VyaXR5X2NvaW5iYXNlX3YxIiwib3VpX3YxIiwic3RhdGVfY2hhbm5lbF9vcGVuX3YxIiwic3RhdGVfY2hhbm5lbF9jbG9zZV92MSIsImdlbl9nYXRld2F5X3YxIiwicm91dGluZ192MSIsInBheW1lbnRfdjEiLCJzZWN1cml0eV9leGNoYW5nZV92MSIsImNvbnNlbnN1c19ncm91cF92MSIsImFkZF9nYXRld2F5X3YxIiwiYXNzZXJ0X2xvY2F0aW9uX3YxIiwiYXNzZXJ0X2xvY2F0aW9uX3YyIiwiY3JlYXRlX2h0bGNfdjEiLCJyZWRlZW1faHRsY192MSIsInBvY19yZXF1ZXN0X3YxIiwicG9jX3JlY2VpcHRzX3YxIiwidmFyc192MSIsInJld2FyZHNfdjEiLCJyZXdhcmRzX3YyIiwidG9rZW5fYnVybl92MSIsImRjX2NvaW5iYXNlX3YxIiwidG9rZW5fYnVybl9leGNoYW5nZV9yYXRlX3YxIiwicGF5bWVudF92MiIsInByaWNlX29yYWNsZV92MSIsInRyYW5zZmVyX2hvdHNwb3RfdjEiLCJ0cmFuc2Zlcl9ob3RzcG90X3YyIiwic3Rha2VfdmFsaWRhdG9yX3YxIiwidW5zdGFrZV92YWxpZGF0b3JfdjEiLCJ0cmFuc2Zlcl92YWxpZGF0b3Jfc3Rha2VfdjEiLCJ2YWxpZGF0b3JfaGVhcnRiZWF0X3YxIiwiY29uc2Vuc3VzX2dyb3VwX2ZhaWx1cmVfdjEiXSwibWluX2Jsb2NrIjo0NzQzMjUsIm1heF9ibG9jayI6MTE0NzEzNiwiYmxvY2siOjExNDcxMDAsImFuY2hvcl9ibG9jayI6MTE0NzEwMH0 HTTP/1.1

< Host: api.helium.io
< User-Agent: heliumacct/0.2.0 CPython/3.9.2 Windows/10
< Accept-Encoding: gzip, deflate
< Accept: */*
< Connection: keep-alive
< 

> HTTP/1.1 500 Internal Server Error
> Connection: keep-alive
> Content-Length: 21
> Access-Control-Allow-Origin: *
> Access-Control-Allow-Credentials: true
> Fastly-Restarts: 1
> Accept-Ranges: bytes
> Date: Mon, 20 Dec 2021 13:13:45 GMT
> Via: 1.1 varnish
> X-Served-By: cache-iad-kiad7000054-IAD
> X-Cache: MISS
> X-Cache-Hits: 0
> X-Timer: S1640005977.803054,VS0,VE48864
> Strict-Transport-Security: max-age=300
> 

Internal server error
```

### Background

A monthly ETL program retrieves account activity and prepares a transaction file, which is imported into an accounting program.
The transaction file should contain all activity since the previous ETL program run, typically a month of activity.

The ETL program has run without fail from May through November 2021.
The most recent successful runs were on 2021-09-05, 2021-10-03, and 2021-11,02.
The December run failed on 2021-12-03.

### Environment

The ETL program is written in Python 3.9.
The program was run on Windows 10, but could run wherever Python runs.
Log times are USA EST.

### Another Example

In the attached log, the Helium Blockchain API returns three pages containing activities before failing with an internal server error.
The ETL program logs each retrieved activity.

[example_log.txt](https://github.com/helium/blockchain-http/files/7748853/example_log.txt)

This example demonstrates that the ETL program correctly handles API cursors and can extract account activities from the Helium Blockchain API response JSON.

**Comment by jshprentz** [comment]
My workaround for this problem was to add a slight delay (0.05 seconds) before each API request.

**Comment by pixabits** [comment]
I haven't found a workaround yet.  I've tried up to a 2-second delay, and I still get the same errors on virtually every cursor call.  It's bringing my systems to a standstill.

**Comment by madninja** [comment]
Please see the relevant announcements on the discord server and in the docs for details, but we'll be removing the activity endpoint soon because there was no way to fix these issues without designing an alternate approach to getting activity without having to fetch all the details.

**Comment by jshprentz** [comment]
Thanks, Marc, for the heads-up about removing the activity endpoint. I'm not sure the API can still be considered version 1 after dropping such a central endpoint.

My application runs monthly to generate reports, so it retrieves a month of activities. Lately, that was about a half dozen pages linked by cursors from the activity endpoint.

As I understand the new roles based approach, a client first retrieves a list of roles (probably a few data pages) and then retrieves each transaction with a separate request. That's hundreds of (admittedly simpler) API requests. I hope that improves server load.

Undocumented is the roles endpoint response when an account performs multiple roles within a transaction. For example, when a hotspot is moved for the tenth time, the same account could be the owner and payer of an assert_location_v2 transaction.

**Comment by madninja** [comment]
> Thanks, Marc, for the heads-up about removing the activity endpoint. I'm not sure the API can still be considered version 1 after dropping such a central endpoint.

I can't disagree, but after talking to a number of folks it seemed like it was easier to announce the removal than to cycle _all_ endpoints to a v2 to then remove all the v1 routes. The API just can't handle the way the activity route was being constructed. 

> 
> My application runs monthly to generate reports, so it retrieves a month of activities. Lately, that was about a half dozen pages linked by cursors from the activity endpoint.
> 
> As I understand the new roles based approach, a client first retrieves a list of roles (probably a few data pages) and then retrieves each transaction with a separate request. That's hundreds of (admittedly simpler) API requests. I hope that improves server load.

It has improved server load considerably, yes
> 
> Undocumented is the roles endpoint response when an account performs multiple roles within a transaction. For example, when a hotspot is moved for the tenth time, the same account could be the owner and payer of an assert_location_v2 transaction.

_All_ roles are listed for a given "actor" in a given transaction yes. If you want to just list the actor _once_ you'll have to de-duplicate on the client side. Explorer and the app both do this today since they prefer not to show multiple roles but just want to show the transaction involved.

**Comment by jshprentz** [comment]
Thanks again, Marc, for your responses.
