### ISSUE TITLE
use recent_activity as proxy for whether a Hotspot is online

### ISSUE THREAD

**Issue by cokes518** [helium/blockchain-http#389]
Instead of relying on gossiped data (that can take hours/days to update) to infer if a Hotspot is online or not, we should use activity.

If a Hotspot has had any of the following activity in the past 180 blocks (or 3 hours), consider it online, otherwise, display `unknown`.

Challenger
Beaconer
Witness
Data Transferred

**Comment by madninja** [comment]
> Instead of relying on gossiped data (that can take hours/days to update) to infer if a Hotspot is online or not, we should use activity.
> 
> If a Hotspot has had any of the following activity in the past 180 blocks (or 3 hours), consider it online, otherwise, display `unknown`.
> 
> Challenger Beaconer Witness Data Transferred

So would we still have the special case fake "online" after onboarding?

**Comment by cokes518** [comment]
it was decided that we will not have a special case of fake "online" after onboarding. hotspots will be offline until they get a snapshot and start having on-chain activity, at which point they will say "online".

**Comment by madninja** [comment]
> it was decided that we will not have a special case of fake "online" after onboarding. hotspots will be offline until they get a snapshot and start having on-chain activity, at which point they will say "online".

And "online" is inferred to mean any on-chain activity in the last 24 hours (of blocks), yeah?
