### ISSUE TITLE
Increase hotspot list page size

### ISSUE THREAD

**Issue by jpmeijers** [helium/blockchain-http#396]
https://github.com/helium/blockchain-http/blob/24e501095279648c909dbfc19065a69c3ee78149/src/bh_route_hotspots.erl#L37

Currently if one wants to fetch a list of hotspots from the api, only 1000 hotspots are returned at a time. To fetch all hostpots would therefore require more than 400 calls to this endpoint. The overhead of all these calls is becoming quite substancial. Have a look at https://cargo.helium.com/ to see how long it takes to load all the hotspots.

Limiting the result size is a good idea, but 1000 is very low. Browsers and other clients should be able to handle 10000 (10k) results quite easily. I've done quite some testing while building TTN Mapper, and I ended up limiting json results from APIs to 10k, as this seems to work well on all devices (at least made after 2010).

Can we increase this limit from 1k to 10k?

**Comment by madninja** [comment]
So ideally cargo should _not_ be paging through 400K+ hotspot entries to make a list. It should either

1.  Have access to a Postgres db do it can query the data it needs directly instead of using an api that wasn't built for it
2. Fetch the list _once_ and only add to the list. Since hotspots are listed in reverse of order added (latest first), it would be able to retrieve and store just a small number before finding hotspots that it has already stored. 
3. Use a tile server like we do for explorer. The tile server used by explorer uses mostly option 2 or a cached version of a nightly export job

**Comment by jpmeijers** [comment]
This depends on the use case of course. For coveragemap.net I do the following:
![helium-coveragemap drawio](https://user-images.githubusercontent.com/948278/148354093-54b04dbf-0b44-4f91-9a20-4cd4ccf85e21.png)

Two things that are very important for the coverage are:
* Is the hotspot online or not (last heard in past day or not)
* Has the hotspot moved

So just paging through the api.helium.com result until an already-seen hotspot is found is not good enough. I need to iterate through all the hotspots to update the last heard/online status and detect if the hotspot has moved or not.

I considered running an ETL instance to have direct access to this data, but running an ETL instance requires a huge server which I can't afford to run for a community project.

You mention a nightly export job. Are these exports publicly available? I can definitely use daily exports for my purpose, although I would have liked higher time resolution than that. Maybe if 12-hourly exports are done that would be a good middle ground.

Another option is to make this hotspots endpoint cache its result, but then again a 1000 entry limit per page will still be too low.

We could also take some inspiration from what Packet Broker does with its gateway list API:
https://mapper.packetbroker.net/api/v2/openapi.json
They have filters on the endpoint:
* distance from coordinates
* only updated since timestamp
* only online gateways
* paging - They also use a page size of 1000, but iterating through the pages here is much faster than on Helium.

In the Packet Broker case I use the "only online gateways" filter.

Adding a tile-server type approach to the helium api does not feel right. Depending on the use case the way tiling is done differently. This should not be dictated by the helium api. And even if one uses tiles, you might have to page per tile, as there could be more than 1000 hotspots in a tile.

**Comment by madninja** [comment]
Sorry I missed responding to you here. Did you get this resolved or do you still need access to a nightly export of all hotspots?

**Comment by jpmeijers** [comment]
No, not resolved. I'm still paging through the whole response I get from the API. This takes really long, and most likely causes a lot of load on the API server. 

Daily (or more frequent) dumps would be great. Then I can load in the dumps rather than paging through the API.

**Comment by madninja** [comment]
> No, not resolved. I'm still paging through the whole response I get from the API. This takes really long, and most likely causes a lot of load on the API server.
> 
> Daily (or more frequent) dumps would be great. Then I can load in the dumps rather than paging through the API.

ok we have the same issues with app/explorer and console projects. They use a hotspot network dump that is generated around midnight every day. Available at `https://snapshots.helium.wtf/mainnet/hotspots/network/<date>.json.gz` where `<data>` is the "max-date" in question.. so like today would be 2022-04-21 since it the 24 hours end at 00:00:00 of 2022-04-21 so includes the 24 hours of 2022-04-20, if that makes sense.

**Comment by jpmeijers** [comment]
Great, that dump should work for me.

Two clarifications though:

* The "last modified time" of the 2022-04-20 dump is 2022-04-20T01:00:32Z. So I assume the export happens one hour after the end of the day in UTC. Is this correct?

* The json does not include a "last heard" for the hotspots. Only a "online" status. Can I assume if a hotspot is marked as "online", it was online at the end of the day, ie. 2022-04-20T00:00:00Z in this case?

**Comment by madninja** [comment]
> Great, that dump should work for me.
> 
> Two clarifications though:
> 
> * The "last modified time" of the 2022-04-20 dump is 2022-04-20T01:00:32Z. So I assume the export happens one hour after the end of the day in UTC. Is this correct?

Correct. 

> * The json does not include a "last heard" for the hotspots. Only a "online" status. Can I assume if a hotspot is marked as "online", it was online at the end of the day, ie. 2022-04-20T00:00:00Z in this case?

Correct. it's as online as ETL knows at the time the json snapshot is taken

**Comment by jpmeijers** [comment]
I think this solves my problem well enough for now. I'd like to see a more real-time solution in the future though. But closing this issue for now.

**Comment by jpmeijers** [comment]
@madninja I've gotten around implementing the fetch of hotspot statuses from the snapshot. I see that every entry in the snapshot has `"online": "online"`. Is this a bug, or does this snapshot only contain hotspots that are online at the time of the dump?

**Comment by madninja** [comment]
It should be a straight json dump of the ETL hotspot data.

**Comment by jpmeijers** [comment]
Does that mean all hotspots in the ETL are online? Somehow it doesn't feel right that all the hotspots in this dump is marked as online.

**Comment by madninja** [comment]
> Does that mean all hotspots in the ETL are online? Somehow it doesn't feel right that all the hotspots in this dump is marked as online.

I just went and downloaded `wget  https://snapshots.helium.wtf/mainnet/hotspots/network/2022-09-19.json.gz` uncompressed it and did:

```
$ grep  offline 2022-09-19.json | wc -l
 343192```

So I'm not sure why you're seeing only online as the value of the "online" attribute at all

**Comment by jpmeijers** [comment]
Ok got it. Seems to work as expected. I must have missed a condition before.

```
2022/09/24 11:29:04 Fetching Helium Snapshot https://snapshots.helium.wtf/mainnet/hotspots/network/2022-09-24.json.gz
2022/09/24 11:29:41 Found 953691 hotspots in snapshot
2022/09/24 11:29:41 Online 609107
2022/09/24 11:29:41 Offline 344584
2022/09/24 11:29:41 Other 0
```
