### ISSUE TITLE
Fetching hotspot takes seemingly far too long

### ISSUE THREAD

**Issue by staha8242** [helium/blockchain-http#419]
Hello,

I am working on creating a companion application to help users better understand information about their hotspots.

My application is taking a very long time to process results. It looks like very simple `GET` requests are taking longer than they should: 

For example calling: 
`GET https://api.helium.io/v1/hotspots/112T2YMThQiVKqmn41G8RHggGbtsW7WynY4vLvc8nHzdMDTZmPCb`

Is often taking me **10-20** seconds to process the results. I suspect for this little amount of data, it shouldn't take this long. 

Are there additional parameters I can add to speed this up? Is the API working as expected? 

![image](https://user-images.githubusercontent.com/23441231/161797149-4c983306-514f-49ae-b7b7-e779d55ab354.png)

**Comment by twisterase** [comment]
Hey @staha8242 having this same issue. Making a separate post so we can bump it up for some help here

**Comment by densone** [comment]
Give it a try now and let me know if the requests are still lagging

**Comment by madninja** [comment]
Please re-open if this is still an issue
