### ISSUE TITLE
Fetching Hotspot Info Delay

### ISSUE THREAD

**Issue by twisterase** [helium/blockchain-http#420]
Hi everyone!

I’m creating a application to manage my helium hotspots and I’m having problems getting timely results. The server is timing out the connection because of the delay.

Sometimes the GET call will be timely and return results in ~7 seconds. Other times the GET call takes over 30 seconds, timing out the request on my app.

@staha8242 reported the same issue: https://github.com/helium/blockchain-http/issues/419

Could anyone clarify if there additional parameters to speed this up or if this is a known issue with the API.

Thanks so much! ☺️

**Comment by madninja** [comment]
It shouldn't be taking this long to get a single hotspot info out.. I know @densone had been work on rate limiting but this actually completes, just takes way, way too long

**Comment by densone** [comment]
We e deployed a bunch of new rate limiting @twisterase . If you can share the types of requests this would also be very helpful to us. Depending on the request you are making your request time will vary greatly. unfortunately there were some big abusers 12 days ago but it’s getting better every day. We also deployed 2 very large database hosts last night. Please feel free to send me more info and happy to look into it.

**Comment by madninja** [comment]
Closing for now
