### ISSUE TITLE
compile Error

### ISSUE THREAD

**Issue by geechain-labs** [helium/blockchain-http#428]
./rebar3 compile
===> Verifying dependencies...
===> Plugin rebar3_eqc does not export init/1. It will not be used.
+ mkdir -p _build/cmake
+ cd _build/cmake
+ type cmake3
+ CMAKE=cmake
+ cmake -DWITH_BUNDLE_SNAPPY=ON -DWITH_BUNDLE_LZ4=ON ../../c_src
-- LZ4 library: /home/secer/helium/blockchain-node/_build/default/lib/rocksdb/_build/cmake/lz4/lib/liblz4.a
-- LZ4 includes: /home/secer/helium/blockchain-node/_build/default/lib/rocksdb/_build/cmake/lz4/include
-- Snappy library: /home/secer/helium/blockchain-node/_build/default/lib/rocksdb/_build/cmake/snappy/lib/libsnappy.a
-- Snappy includes: /home/secer/helium/blockchain-node/_build/default/lib/rocksdb/_build/cmake/snappy/include
-- cmake args -DCMAKE_POSITION_INDEPENDENT_CODE=ON;-DCMAKE_CXX_COMPILER=/usr/bin/c++;-DCMAKE_AR=/usr/bin/ar;-DCMAKE_BUILD_TYPE=Release;-DFAIL_ON_WARNINGS=OFF;-DPORTABLE=ON;-DUSE_RTTI=1;-DWITH_TOOLS=OFF;-DWITH_TESTS=OFF;-DWITH_GFLAGS=OFF;-DWITH_JEMALLOC=OFF;-DWITH_TBB=;-DWITH_SNAPPY=TRUE;-DWITH_LZ4=TRUE;-DWITH_ZLIB=;-DWITH_BZ2=;-DWITH_ZSTD=;-Dsnappy_ROOT_DIR=/home/secer/helium/blockchain-node/_build/default/lib/rocksdb/_build/cmake/snappy;-Dlz4_ROOT_DIR=/home/secer/helium/blockchain-node/_build/default/lib/rocksdb/_build/cmake/lz4
-- Found RocksDB library: /home/secer/helium/blockchain-node/_build/default/lib/rocksdb/_build/cmake/rocksdb-prefix/src/rocksdb-build/librocksdb.a
-- Found RocksDB includes: /home/secer/helium/blockchain-node/_build/default/lib/rocksdb/c_src/../deps/rocksdb/include
-- Using OTP lib: /usr/lib/erlang/lib - found
-- Using erl_interface version: erl_interface-5.3
-- Using erts version: erts-13.0
-- Configuring done
-- Generating done
-- Build files have been written to: /home/secer/helium/blockchain-node/_build/default/lib/rocksdb/_build/cmake
+ echo done.
done.
HEAD is now at 659b1d9 version 2.2.0
make[1]: Entering directory '/home/secer/helium/blockchain-node/_build/default/lib/erlang_stats/c_src'
make[1]: '/home/secer/helium/blockchain-node/_build/default/lib/erlang_stats/c_src/../priv/erlang_stats.so' is up to date.
make[1]: Leaving directory '/home/secer/helium/blockchain-node/_build/default/lib/erlang_stats/c_src'
   Compiling multihash v0.0.1 (/home/secer/helium/blockchain-node/_build/default/lib/multihash)
    Finished release [optimized] target(s) in 0.50s
===> Compiling c_src/aead.c
===> Compiling c_src/enacl.c
===> Compiling c_src/enacl_ext.c
===> Compiling c_src/enacl_nif.c
===> Compiling c_src/generichash.c
===> Compiling c_src/hash.c
===> Compiling c_src/kdf.c
===> Compiling c_src/kx.c
===> Compiling c_src/public.c
===> Compiling c_src/pwhash.c
===> Compiling c_src/randombytes.c
===> Compiling c_src/secret.c
===> Compiling c_src/secretstream.c
===> Compiling c_src/sign.c
make[1]: Entering directory '/home/secer/helium/blockchain-node/_build/default/lib/ecc_compact/c_src'
make[1]: '/home/secer/helium/blockchain-node/_build/default/lib/ecc_compact/c_src/../priv/ecc_compact.so' is up to date.
make[1]: Leaving directory '/home/secer/helium/blockchain-node/_build/default/lib/ecc_compact/c_src'
make[1]: Entering directory '/home/secer/helium/blockchain-node/_build/default/lib/inert/c_src'
make[1]: '/home/secer/helium/blockchain-node/_build/default/lib/inert/c_src/../priv/inert_drv.so' is up to date.
make[1]: Leaving directory '/home/secer/helium/blockchain-node/_build/default/lib/inert/c_src'
make[1]: Entering directory '/home/secer/helium/blockchain-node/_build/default/lib/procket/c_src'
make -f /home/secer/helium/blockchain-node/_build/default/lib/procket/c_src/Makefile.ancillary
make[2]: Entering directory '/home/secer/helium/blockchain-node/_build/default/lib/procket/c_src'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/secer/helium/blockchain-node/_build/default/lib/procket/c_src'
cc -m64 -DHAVE_SETNS -g -Wall -o /home/secer/helium/blockchain-node/_build/default/lib/procket/priv/procket -L/home/secer/helium/blockchain-node/_build/default/lib/procket/c_src procket_cmd.c -lancillary
cc /home/secer/helium/blockchain-node/_build/default/lib/procket/c_src/procket.o -shared -L/home/secer/helium/blockchain-node/_build/default/lib/procket/c_src -lancillary -o /home/secer/helium/blockchain-node/_build/default/lib/procket/c_src/../priv/procket.so
make[1]: Leaving directory '/home/secer/helium/blockchain-node/_build/default/lib/procket/c_src'
make[1]: Entering directory '/home/secer/helium/blockchain-node/_build/default/lib/splicer/c_src'
make[1]: '/home/secer/helium/blockchain-node/_build/default/lib/splicer/c_src/../priv/splicer.so' is up to date.
make[1]: Leaving directory '/home/secer/helium/blockchain-node/_build/default/lib/splicer/c_src'
    Finished release [optimized] target(s) in 0.01s
===> The erlang version 25.0 is newer then the latest version known to rebar_erl_vsn (21). Features introduced between after 21 will not have flags.
make[1]: Entering directory '/home/secer/helium/blockchain-node/_build/default/lib/xxhash/c_src'
make[1]: '/home/secer/helium/blockchain-node/_build/default/lib/xxhash/c_src/../priv/xxhash.so' is up to date.
make[1]: Leaving directory '/home/secer/helium/blockchain-node/_build/default/lib/xxhash/c_src'
-- Using upstream h3 tag v3.6.4 based on local tag v3.6.4-37-g90e1b6e
-- Configuring done
-- Generating done
-- Build files have been written to: /home/secer/helium/blockchain-node/_build/default/lib/h3/_build/c_src
make[1]: Entering directory '/home/secer/helium/blockchain-node/_build/default/lib/h3/_build/c_src'
make[2]: Entering directory '/home/secer/helium/blockchain-node/_build/default/lib/h3/_build/c_src'
make[3]: Entering directory '/home/secer/helium/blockchain-node/_build/default/lib/h3/_build/c_src'
make[3]: Leaving directory '/home/secer/helium/blockchain-node/_build/default/lib/h3/_build/c_src'
make[3]: Entering directory '/home/secer/helium/blockchain-node/_build/default/lib/h3/_build/c_src'
[  9%] Performing update step for 'external-h3'
[ 18%] Performing configure step for 'external-h3'
CMake Warning at CMakeLists.txt:261 (message):
  clang-format was not detected, so automatic source code reformatting is
  disabled

CMake Warning at CMakeLists.txt:273 (message):
  clang-tidy was not detected, so source code linting is disabled

-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE) 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/secer/helium/blockchain-node/_build/default/lib/h3/_build/c_src/external-h3/src/external-h3-build
[ 27%] Performing build step for 'external-h3'
make[4]: Entering directory '/home/secer/helium/blockchain-node/_build/default/lib/h3/_build/c_src/external-h3/src/external-h3-build'
make[5]: Entering directory '/home/secer/helium/blockchain-node/_build/default/lib/h3/_build/c_src/external-h3/src/external-h3-build'
make[6]: Entering directory '/home/secer/helium/blockchain-node/_build/default/lib/h3/_build/c_src/external-h3/src/external-h3-build'
make[6]: Leaving directory '/home/secer/helium/blockchain-node/_build/default/lib/h3/_build/c_src/external-h3/src/external-h3-build'
[100%] Built target h3
make[5]: Leaving directory '/home/secer/helium/blockchain-node/_build/default/lib/h3/_build/c_src/external-h3/src/external-h3-build'
make[4]: Leaving directory '/home/secer/helium/blockchain-node/_build/default/lib/h3/_build/c_src/external-h3/src/external-h3-build'
[ 36%] Performing install step for 'external-h3'
make[4]: Entering directory '/home/secer/helium/blockchain-node/_build/default/lib/h3/_build/c_src/external-h3/src/external-h3-build'
make[5]: Entering directory '/home/secer/helium/blockchain-node/_build/default/lib/h3/_build/c_src/external-h3/src/external-h3-build'
make[6]: Entering directory '/home/secer/helium/blockchain-node/_build/default/lib/h3/_build/c_src/external-h3/src/external-h3-build'
make[6]: Leaving directory '/home/secer/helium/blockchain-node/_build/default/lib/h3/_build/c_src/external-h3/src/external-h3-build'
[100%] Built target h3
make[5]: Leaving directory '/home/secer/helium/blockchain-node/_build/default/lib/h3/_build/c_src/external-h3/src/external-h3-build'
Install the project...
-- Install configuration: ""
-- Up-to-date: /home/secer/helium/blockchain-node/_build/default/lib/h3/_build/c_src/lib/libh3.a
-- Up-to-date: /home/secer/helium/blockchain-node/_build/default/lib/h3/_build/c_src/include/h3/h3api.h
-- Up-to-date: /home/secer/helium/blockchain-node/_build/default/lib/h3/_build/c_src/lib/cmake/h3/h3Config.cmake
-- Up-to-date: /home/secer/helium/blockchain-node/_build/default/lib/h3/_build/c_src/lib/cmake/h3/h3ConfigVersion.cmake
-- Up-to-date: /home/secer/helium/blockchain-node/_build/default/lib/h3/_build/c_src/lib/cmake/h3/h3Targets.cmake
-- Installing: /home/secer/helium/blockchain-node/_build/default/lib/h3/_build/c_src/lib/cmake/h3/h3Targets-noconfig.cmake
make[4]: Leaving directory '/home/secer/helium/blockchain-node/_build/default/lib/h3/_build/c_src/external-h3/src/external-h3-build'
[ 45%] Completed 'external-h3'
make[3]: Leaving directory '/home/secer/helium/blockchain-node/_build/default/lib/h3/_build/c_src'
[ 72%] Built target external-h3
make[3]: Entering directory '/home/secer/helium/blockchain-node/_build/default/lib/h3/_build/c_src'
make[3]: Leaving directory '/home/secer/helium/blockchain-node/_build/default/lib/h3/_build/c_src'
[100%] Built target h3
make[2]: Leaving directory '/home/secer/helium/blockchain-node/_build/default/lib/h3/_build/c_src'
Install the project...
-- Install configuration: "Release"
-- Up-to-date: /home/secer/helium/blockchain-node/_build/default/lib/h3/c_src/../priv/libh3.so
make[1]: Leaving directory '/home/secer/helium/blockchain-node/_build/default/lib/h3/_build/c_src'
    Finished release [optimized] target(s) in 0.01s
make[1]: Entering directory '/home/secer/helium/blockchain-node/_build/default/lib/exor_filter/c_src'
make[1]: '/home/secer/helium/blockchain-node/_build/default/lib/exor_filter/c_src/../priv/exor_filter.so' is up to date.
make[1]: Leaving directory '/home/secer/helium/blockchain-node/_build/default/lib/exor_filter/c_src'
    Finished release [optimized] target(s) in 0.02s
make[1]: Entering directory '/home/secer/helium/blockchain-node/_build/default/lib/blockchain'
blockchain core grpc service directory  does not exist
./rebar3 get-deps
=ERROR REPORT==== 8-Jun-2022::09:04:36.319386 ===
beam/beam_load.c(148): Error loading module rebar3:
  please re-compile this module with an Erlang/OTP 25 compiler

escript: exception error: undefined function rebar3:main/1
  in function  escript:run/2 (escript.erl, line 750)
  in call from escript:start/1 (escript.erl, line 277)
  in call from init:start_em/1 
  in call from init:do_boot/3 
make[1]: *** [GNUmakefile:44: src/grpc/autogen] Error 127
make[1]: Leaving directory '/home/secer/helium/blockchain-node/_build/default/lib/blockchain'
===> Hook for compile failed!

make: *** [Makefile:18: compile] Error 1

**Comment by madninja** [comment]
Erlang 25 was recently released and is not supported yet. Please use erlang 24
