### ISSUE TITLE
Snapshots not being updated

### ISSUE THREAD

**Issue by jpmeijers** [helium/blockchain-http#444]
Refer to #396 and https://github.com/helium/blockchain-http/issues/396#issuecomment-1103936930

When trying to access the latest snapshot using url https://snapshots.helium.wtf/mainnet/hotspots/network/2023-06-05.json.gz, I get an access denied error. All snapshots up to 2023-06-02 work, but from 2023-06-03 they do not.

**Comment by madninja** [comment]
The old Helium L1 was halted on April 16, 2023.. All account state was moved to the Solana blockchain.

**Comment by jpmeijers** [comment]
What would be the new alternative to these snapshots?
